config/routes.rb
Rails.application.routes.draw do
  
  #loader.io
  get '/loaderio-7fe46fa08629e24bafdce9f722b81934', to: 'home#loaderio'
  
  get '/basics', to: 'home#basics'

  get '/ruby', to: 'home#ruby'

  get '/git', to: 'home#git'
  
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def home
    @local_time = Time.now.localtime("-05:00") 
  end
  
  def basics
  end

  def ruby
  end

  def git
  end
  
  def loaderio
    render html: "loaderio-7fe46fa08629e24bafdce9f722b81934"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/basics.html.erb
<h1>Basics</h1>
<p>Respuesta a preguntas:</p>
<ul>
<li>Resource: Es una "Cosa" (ej: un modelo en RoR) en internet que puede ser "encontrada", "descrita" y "modificada" por una URI.</li>
<li>RESTFull Routing deja manipular un Resource por medio de operaciones stataless</li>
<li>La idea es permitir una interfaz CRUD sobre el resource utilizando los m&eacute;todos HTTP: GET, PUT, POST, DELETE (puede que PATCH)</li>
</ul>

app/views/home/git.html.erb
<h1>Git</h1>
<ul>
<li>Inicializaci&oacute;n de un repositorio de git nuevo en una aplicaci&oacute;n existente
<ul>
<li>git init</li>
</ul>
</li>
<li>Creaci&oacute;n de un branch nuevo
<ul>
<li>git checkout -b branch</li>
</ul>
</li>
<li>Realizar un commit incluyendo todos los cambios actuales
<ul>
<li>git add - A&nbsp;</li>
<li>git commit -m "mensaje"</li>
</ul>
</li>
<li>C&oacute;mo enviar el c&oacute;digo al repositorio remoto
<ul>
<li>git push origin master</li>
</ul>
</li>
<li>C&oacute;mo configurar el origen del repositorio remoto para evitar escribirlo<br />siempre cada vez que se hace un push o un pull.
<ul>
<li>&iquest;C&oacute;mo?</li>
</ul>
</li>
<li>Diferencia entre un reset y revert
<ul>
<li>Reset es como un rollback a un commit previo (cuando la embarr&eacute; comon undo)</li>
<li>Revert es como un cancel para eliminar todo pues hace un nuevo commit</li>
</ul>
</li>
<li>Adem&aacute;s de cambiar de ramas, para qu&eacute; m&aacute;s se puede utilizar el comando git<br />checkout
<ul>
<li>Para crear una nueva rama, detach y patch</li>
</ul>
</li>
<li>Como puede ver los commits que se han realizado en el proyecto
<ul>
<li>git log</li>
</ul>
</li>
<li>He modificado dos archivos y quiero hacer un commit por cada uno de ellos,<br />c&oacute;mo lo puedo hacer?
<ul>
<li>Muchas formas, uno puede ser agregar el cambio de cada uno (omitiendo el cambio de un archivo en el primerio, sin hacerle track) en un comit distingo o hacer 2 branches y en cada uno hacer un cambio en el archivo.</li>
</ul>
</li>
</ul>

app/views/home/home.html.erb
<h1>This is home</h1>
<p>This is now (UTC-5): <%= @local_time.to_s(:long)%> </p>

app/views/home/ruby.html.erb
<h1>Ruby</h1>
<p>Resumen de Ruby</p>
<p><strong>1</strong> Interpolaci&oacute;n de strings: "Valor de una variable: #{@variable}"<br /><strong>2&nbsp;</strong>C&oacute;mo se declara un array y c&oacute;mo se adiciona un elemento al final del array:</p>
<blockquote>
<p><code>a = [] &oacute; a = Array.new<br />a &gt;&gt; 1 &oacute; a.push(1)</code></p>
</blockquote>
<p><strong>3&nbsp;</strong>C&oacute;mo se itera un array utilizando el comando each</p>
<blockquote><code>a.each do |i| <br /> &nbsp;&nbsp;&nbsp;&nbsp;puts i <br />end</code></blockquote>
<p><strong>4&nbsp;</strong>C&oacute;mo se declara un hash</p>
<p><code>h = {} &oacute; h = Hash.new</code></p>
<p><strong>5&nbsp;</strong>C&oacute;mo se itera un hash utilizando el comando each</p>
<p><code>h.each do |key, value| <br /> 	 &nbsp;&nbsp;&nbsp;&nbsp; puts "Valor de #{key} es #{value}" <br />end</code></p>
<p><strong>6&nbsp;</strong>Que es un block en ruby? De un ejemplo de c&oacute;mo utilizarlo</p>
<p>Es un shortcut de c&oacute;digo para escribir m&aacute;s corto, por ejemplo recorrer un array as&iacute;</p>
<blockquote><code>a.each{|i| puts i}</code></blockquote>
<p><strong>7&nbsp;</strong>Cual es la convenci&oacute;n en Ruby a la hora de nombrar variables?: snake_case</p>
<p><br /><strong>8&nbsp;</strong>Qu&eacute; son attr_reader, attr_writer y attr_accesor? Para qu&eacute; sirven?</p>
<p>M&eacute;todos dentro de una clase para poder acceder a sus attributos</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hogaru1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to image_tag("https://www.hogaru.com/assets/logo_hogaru-59b8dca05b7190d5b9bcfb9a85515ff2d9154eb29e705d63738c08da3a886a5e.svg", class: "img-logo"), root_path %>
        <p class="logo_text">bootcamp</p>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Basics", basics_path %></li>
            <li><%= link_to "Ruby", ruby_path %></li>
            <li><%= link_to "Git", git_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>